# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 최효린
title: 서버 백엔드 개발자
email: yoinoichr@gmail.com
# website: www.github.com/hyorin

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: hyorin
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: velog
#   icon: fa-pen-nib
#   url: https://velog.io/@chyr
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Java & Spring, Netty & Chromium & gRPC Framework, HTML5 기반의 6년차 서버 개발자입니다.

  방송 미디어 관련 회사에서 신규 프로젝트의 TF팀부터 시작하여, 국내 8개의 T-Commerce 고객 사 및 해외 1억 5000만 명에 이르는 대규모 IPTV 플랫폼에서 백엔드 서비스 개발 및 인프라 구축 등을 해왔습니다.

  설계 단계부터 UML 다이어그램을 작성하고 팀 구성원들과 적극적으로 커뮤니케이션 함으로써 보다 간결하고 이해하기 쉬운 코드를 만들려고 노력합니다.

  <mark>주요 스킬</mark> Java, Spring Boot, Netty, HAProxy, MyBatis, gRPC, Chromium Embeded Framework

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 에어코드
        link: www.aircode.com
        # link_text: boringcompany.com
        sub_title: Backend 개발자
        caption: 2017.12 - 현재
        quote: >
          원격 브라우저 격리(RBI) 솔루션 R&D
        description: | # this will include new lines to allow paragraphs
          - 웹 브라우저 화면을 W3C 표준 기준 DOM 정보로 분해 및 재구성
          - 국내외 다수 도메인의 CSS, Script 분석 및 폴리필 작성 경험
          - Spring Security 활용한 API Filter 개발
      - layout: left
        quote: >
          국내 8개의 T-Commerce 고객 사 및 해외 1억 5000만 명에 이르는 대규모 IPTV 플랫폼 서비스 구축
        description: | # this will include new lines to allow paragraphs
          - IPTV 플랫폼 셋탑박스와 연결된 TV 화면에서 가상 웹 브라우징 화면을 연동하는 서비스 개발
          - 레거시 시스템의 코드 파편화 등 문제점 보완하고, 고가용성과 무중단 배포가 가능한 시스템으로 전환
          - AWS, NHN Cloud(Toast) 환경에서 서비스 구축 경험
          - 2020' <mark>최우수사원</mark>, 2021' <mark>우수사원</mark> 수상

  - title: 역량 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 오픈소스/표준 활용
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        # - title:  sproogen/modern-resume-theme
        #   icon: fab fa-github
        #   url: github.com/sproogen/modern-resume-theme
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          - 5년 넘는 기간동안 Chromium Embeded Framework(CEF) 오픈소스 분석/개발 경험
          - Java CEF 에서 발생하는 Memory Leak 해결 (Jmap, JvisualVM 사용)
          - WebRTC 활용한 서버-클라이언트 간 Video 동기화
          - JWT, OAuth 통한 인증된 사용자 확인 및 외부 리소스 요청 Proxy
          - 갑작스런 정전 등 서버 간 연동이 끊어질 때, 전송 중이던 데이터 유실 문제를 gRPC와 SQLite를 이용하여 해결

      - layout: top-middle
        title: 대용량 트래픽 분산/ 대역폭 감소
        description: | # this will include new lines to allow paragraphs
          - 일 평균 3만 건의 IPTV 셋탑박스 앱 클라이언트 접속 분산을 위한 HAProxy 적용 경험
          - 이미지 캐싱, PNG Optimize 적용하여 세션 당 대역폭 40% 감소
          - 사용자의 접속 주소(Region) 에 기반하여 물리적 거리가 가까운 클러스터로 접속하도록 시스템 구축
          - Sharding Sphere 적용하여 내부 시스템 간 트래픽 처리 성능을 2000/s -> 120,000/s 으로 개선

      # - layout: top-middle
      #   title: 타 팀과의 연계 개발 경험
      #   description: | # this will include new lines to allow paragraphs
      #     - 셋탑박스 제조사마다 다르게 사용되는 연결 프로토콜(Socket, WebSocket, Socket.IO) 에 각기 다른 Netty Framework 의 Handler 를 연결하고, ByteBuf 를 연동규격에 따라 encode/decode 처리.
      #     - 특히, TV 셋탑박스에 구동된 LiteClient 와, 플랫폼사 WAS 서비스 간 연동을 중간자 입장에서 처리하기 위해, 본인이 맡은 부분 외에도 다른 팀의 프로젝트들 모두 분석, Trouble shooting 경험
      #     - 서비스 구축을 위해 항상 5~10명의 내/외부 개발 인원과 교류하며 업무 진행
      #     - 그 공로를 인정받아 2021’ 최우수사원, 2020’ 우수사원을 수상함

      - layout: top-middle
        title: DevOps
        description: | # this will include new lines to allow paragraphs
          - 사내 SVN to Git 전환 경험
          - Maven, Jenkins, Nexus 로 CI/CD 관리

  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: center
        quote: >
          현재 업무에 사용중 혹은 사용했던 기술들입니다.
      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          - Java, Javascript, C++
          - Spring Boot, Spring Security, Chromium, Netty, gRPC, MyBatis
          - MariaDB, Oracle
          - AWS, Toast, Git, Maven
          - Eclipse, Visual Studio Code

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     음.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
